name: Migrate Test
on:
  push:
    branches:
      - main
jobs:
  migrate_test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SUPERUSER_PASSWORD: mock_password
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Create a virtual environment
        run: | 
          python3 -m venv .venv
          source .venv/bin/activate
      - name: Install Django REST Framework into the virtual env
        run: pip install djangorestframework
      - name: Check for structural DB changes
        run: python manage.py makemigrations
      - name: Sync the SQLite database
        run: python manage.py migrate
      - name: Create the admin user
        run: |
          python manage.py createsuperuser --noinput --username admin --email admin@example.com
      - name: Run the app
        run: |
          nohup python manage.py runserver & sleep 5
      - name: Access the API
        run: |
          curl -u admin:${{ env.DJANGO_SUPERUSER_PASSWORD }} -H 'Accept: application/json; indent=4' http://127.0.0.1:8000/users/
          curl -u admin:${{ env.DJANGO_SUPERUSER_PASSWORD }} -H 'Accept: application/json; indent=4' http://127.0.0.1:8000/groups/
          curl -u admin:${{ env.DJANGO_SUPERUSER_PASSWORD }} -H 'Accept: application/json; indent=4' http://127.0.0.1:8000/companies/